/*
 * buildopts.h 
 * Automatically generated
 */

#define LOADABLE_MODULES 1
#define OPTIONAL_API 1
#define AST_MODULE_BRIDGE_HOLDING 1
#define AST_MODULE_APP_CDR 1
#define AST_MODULE_APP_CONFBRIDGE 1
#define AST_MODULE_RES_MONITOR 1
#define AST_MODULE_RES_SPEECH 1
#define AST_MODULE_RES_AGI 1
#define AST_MODULE_RES_STASIS 1
#define AST_MODULE_RES_ADSI 1
#define AST_MODULE_RES_SMDI 1
#define AST_MODULE_RES_ODBC 1
#define AST_MODULE_RES_PJSIP 1
#define AST_MODULE_RES_PJSIP_SESSION 1
#define AST_MODULE_RES_CRYPTO 1
#define AST_MODULE_RES_HTTP_WEBSOCKET 1
#define AST_MODULE_APP_CHANSPY 1
#define AST_MODULE_FUNC_CUT 1
#define AST_MODULE_FUNC_GROUPCOUNT 1
#define AST_MODULE_FUNC_URI 1
#define AST_MODULE_RES_AEL_SHARE 1
#define AST_MODULE_RES_ARI 1
#define AST_MODULE_RES_SORCERY_CONFIG 1
#define AST_MODULE_RES_SORCERY_MEMORY 1
#define AST_MODULE_RES_SORCERY_ASTDB 1
#define AST_MODULE_RES_PJSIP_PUBSUB 1
#define AST_MODULE_RES_PJSIP_EXTEN_STATE 1
#define AST_MODULE_RES_PJSIP_OUTBOUND_PUBLISH 1
#define AST_MODULE_RES_STASIS_RECORDING 1
#define AST_MODULE_RES_HEP 1
#define AST_MODULE_RES_PHONEPROV 1
#define AST_MODULE_G711_NEW_ALGORITHM 1
#define AST_BUILDOPT_SUM "5504baa4b56df6de8416c75ac66a1b90"
#define AST_BUILDOPTS "LOADABLE_MODULES, OPTIONAL_API"
